// <auto-generated />
using EntidadesDePropiedad;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntidadesDePropiedad.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200422143114_DatosEstudiante")]
    partial class DatosEstudiante
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntidadesDePropiedad.Models.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("EntidadesDePropiedad.Models.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Felipe"
                        });
                });

            modelBuilder.Entity("EntidadesDePropiedad.Models.Contacto", b =>
                {
                    b.HasOne("EntidadesDePropiedad.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EntidadesDePropiedad.Models.Direccion", "Casa", b1 =>
                        {
                            b1.Property<int>("ContactoId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Calle")
                                .HasColumnName("Calle")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Ciudad")
                                .HasColumnName("Ciudad")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ContactoId");

                            b1.ToTable("Contactos");

                            b1.WithOwner()
                                .HasForeignKey("ContactoId");
                        });
                });

            modelBuilder.Entity("EntidadesDePropiedad.Models.Estudiante", b =>
                {
                    b.OwnsOne("EntidadesDePropiedad.Models.Direccion", "BillingAddress", b1 =>
                        {
                            b1.Property<int>("EstudianteId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Calle")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Ciudad")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EstudianteId");

                            b1.ToTable("Estudiantes");

                            b1.WithOwner()
                                .HasForeignKey("EstudianteId");
                        });

                    b.OwnsOne("EntidadesDePropiedad.Models.Direccion", "Casa", b1 =>
                        {
                            b1.Property<int>("EstudianteId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Calle")
                                .HasColumnName("Calle")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Ciudad")
                                .HasColumnName("Ciudad")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EstudianteId");

                            b1.ToTable("Estudiantes");

                            b1.WithOwner()
                                .HasForeignKey("EstudianteId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
