// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace EFCorePeliculas.CompiledModels
{
    public partial class ApplicationDbContextModel
    {
        partial void Initialize()
        {
            var actor = ActorEntityType.Create(this);
            var direccion = DireccionEntityType.Create(this);
            var direccion0 = Direccion0EntityType.Create(this);
            var cine = CineEntityType.Create(this);
            var direccion1 = Direccion1EntityType.Create(this);
            var cineDetalle = CineDetalleEntityType.Create(this);
            var cineOferta = CineOfertaEntityType.Create(this);
            var genero = GeneroEntityType.Create(this);
            var log = LogEntityType.Create(this);
            var mensaje = MensajeEntityType.Create(this);
            var pago = PagoEntityType.Create(this);
            var pelicula = PeliculaEntityType.Create(this);
            var peliculaActor = PeliculaActorEntityType.Create(this);
            var persona = PersonaEntityType.Create(this);
            var producto = ProductoEntityType.Create(this);
            var salaDeCine = SalaDeCineEntityType.Create(this);
            var cineSinUbicacion = CineSinUbicacionEntityType.Create(this);
            var peliculaConConteos = PeliculaConConteosEntityType.Create(this);
            var generoPelicula = GeneroPeliculaEntityType.Create(this);
            var peliculaSalaDeCine = PeliculaSalaDeCineEntityType.Create(this);
            var merchandising = MerchandisingEntityType.Create(this, producto);
            var pagoPaypal = PagoPaypalEntityType.Create(this, pago);
            var pagoTarjeta = PagoTarjetaEntityType.Create(this, pago);
            var peliculaAlquilable = PeliculaAlquilableEntityType.Create(this, producto);

            DireccionEntityType.CreateForeignKey1(direccion, actor);
            Direccion0EntityType.CreateForeignKey1(direccion0, actor);
            Direccion1EntityType.CreateForeignKey1(direccion1, cine);
            CineDetalleEntityType.CreateForeignKey1(cineDetalle, cine);
            CineOfertaEntityType.CreateForeignKey1(cineOferta, cine);
            MensajeEntityType.CreateForeignKey1(mensaje, persona);
            MensajeEntityType.CreateForeignKey2(mensaje, persona);
            PeliculaActorEntityType.CreateForeignKey1(peliculaActor, actor);
            PeliculaActorEntityType.CreateForeignKey2(peliculaActor, pelicula);
            SalaDeCineEntityType.CreateForeignKey1(salaDeCine, cine);
            GeneroPeliculaEntityType.CreateForeignKey1(generoPelicula, genero);
            GeneroPeliculaEntityType.CreateForeignKey2(generoPelicula, pelicula);
            PeliculaSalaDeCineEntityType.CreateForeignKey1(peliculaSalaDeCine, pelicula);
            PeliculaSalaDeCineEntityType.CreateForeignKey2(peliculaSalaDeCine, salaDeCine);
            MerchandisingEntityType.CreateForeignKey1(merchandising, producto);
            PeliculaAlquilableEntityType.CreateForeignKey1(peliculaAlquilable, producto);

            GeneroEntityType.CreateSkipNavigation1(genero, pelicula, generoPelicula);
            PeliculaEntityType.CreateSkipNavigation1(pelicula, genero, generoPelicula);
            PeliculaEntityType.CreateSkipNavigation2(pelicula, salaDeCine, peliculaSalaDeCine);
            SalaDeCineEntityType.CreateSkipNavigation1(salaDeCine, pelicula, peliculaSalaDeCine);

            ActorEntityType.CreateAnnotations(actor);
            DireccionEntityType.CreateAnnotations(direccion);
            Direccion0EntityType.CreateAnnotations(direccion0);
            CineEntityType.CreateAnnotations(cine);
            Direccion1EntityType.CreateAnnotations(direccion1);
            CineDetalleEntityType.CreateAnnotations(cineDetalle);
            CineOfertaEntityType.CreateAnnotations(cineOferta);
            GeneroEntityType.CreateAnnotations(genero);
            LogEntityType.CreateAnnotations(log);
            MensajeEntityType.CreateAnnotations(mensaje);
            PagoEntityType.CreateAnnotations(pago);
            PeliculaEntityType.CreateAnnotations(pelicula);
            PeliculaActorEntityType.CreateAnnotations(peliculaActor);
            PersonaEntityType.CreateAnnotations(persona);
            ProductoEntityType.CreateAnnotations(producto);
            SalaDeCineEntityType.CreateAnnotations(salaDeCine);
            CineSinUbicacionEntityType.CreateAnnotations(cineSinUbicacion);
            PeliculaConConteosEntityType.CreateAnnotations(peliculaConConteos);
            GeneroPeliculaEntityType.CreateAnnotations(generoPelicula);
            PeliculaSalaDeCineEntityType.CreateAnnotations(peliculaSalaDeCine);
            MerchandisingEntityType.CreateAnnotations(merchandising);
            PagoPaypalEntityType.CreateAnnotations(pagoPaypal);
            PagoTarjetaEntityType.CreateAnnotations(pagoTarjeta);
            PeliculaAlquilableEntityType.CreateAnnotations(peliculaAlquilable);

            AddAnnotation("ProductVersion", "6.0.1");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
